name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm web build:only

      - name: Generate CNAME
        run: |
          mkdir -p apps/web/dist
          echo "markdown.yahweh.top" > apps/web/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: apps/web/dist
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: wyw-s/markdown-wechat
